import {
  BookItem,
  VideoItem,
  PhotoItem,
  SpiritualTopic,
  HolyScripture,
  SocialReform,
  AnnapurnaInitiative,
  AnnapurnaStory,
  UpdateItem,
  FAQItem,
  AshramContact,
  FeaturedMediaItem,
} from './types';

export const OFFICIAL_CHANNELS = {
  jagatUddharakYoutube: 'https://www.youtube.com/@JagatUddharak',
  jagatUddharakFacebook: 'https://www.facebook.com/JagatUddharak',
  santRampalJiInstagram: 'https://www.instagram.com/spiritualleadersaintrampalji/',
  annapurnaMuhimInstagram: 'https://www.instagram.com/annapurnamuhim/',
  annapurnaMuhimWebsite: 'https://annapurnamuhim.com/',
  annapurnaMuhimYoutube: 'https://www.youtube.com/@AnnapurnaMuhimofficial',
  factfulDebatesYoutube: 'https://www.youtube.com/@FactfulDebates',
  saTrueStoryYoutube: 'https://www.youtube.com/@SATrueStoryOfficial/videos',
  officialWebsite: 'https://www.jagatgururampalji.org/hi/',
  officialBooksSite: 'https://books.jagatgururampalji.org/',
};

// 100% matched Book Cover + Title + Description + Read URL + PDF URL from official portal
export const BOOKS_DATA: BookItem[] = [
  {
    id: 'gyan-ganga',
    title: 'ज्ञान गंगा',
    titleEn: 'Gyan Ganga',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/gyan-ganga-hindi.webp',
    description: 'सभी धर्मों के पवित्र सद्ग्रंथों (वेद, गीता, कुरान, बाइबल, गुरु ग्रंथ साहिब) के प्रमाणों पर आधारित अद्वितीय आध्यात्मिक तत्वज्ञान पुस्तक।',
    descriptionEn: 'An extraordinary spiritual masterpiece revealing authentic scripture proofs from the Vedas, Gita, Quran, Bible, and Guru Granth Sahib.',
    readUrl: 'https://books.jagatgururampalji.org/gyan-ganga-hindi',
    pdfUrl: 'https://www.jagatgururampalji.org/gyan_ganga_hindi.pdf',
    category: 'मुख्य आध्यात्मिक साहित्य',
    categoryEn: 'Core Spiritual Literature',
    language: 'हिन्दी / English',
    featured: true,
  },
  {
    id: 'jeene-ki-rah',
    title: 'जीने की राह',
    titleEn: 'Way of Living',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/jeene-ki-rah-hindi.webp',
    description: 'मानव जीवन को सुखी, सदाचारी, नशामुक्त, और मर्यादित बनाने हेतु प्रत्येक परिवार के लिए अनिवार्य मार्गदर्शक ग्रंथ।',
    descriptionEn: 'An essential practical guide for every household to live a virtuous, addiction-free, and blissful life.',
    readUrl: 'https://books.jagatgururampalji.org/jeene-ki-rah',
    pdfUrl: 'https://www.jagatgururampalji.org/jeene-ki-rah.pdf',
    category: 'समाज सुधार व जीवन दर्शन',
    categoryEn: 'Social Reform & Life Philosophy',
    language: 'हिन्दी / English',
    featured: true,
  },
  {
    id: 'gita-tera-gyan-amrit',
    title: 'गीता तेरा ज्ञान अमृत',
    titleEn: 'Gita Tera Gyan Amrit',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/gita-tera-gyan-amrit-hindi.webp',
    description: 'श्रीमद्भगवद्गीता के गूढ़ रहस्यों का यथार्थ आध्यात्मिक विश्लेषण और वास्तविक मोक्षदायक भक्ति विधि।',
    descriptionEn: 'The profound, authentic spiritual explanation of the Shrimad Bhagavad Gita and the genuine path of complete salvation.',
    readUrl: 'https://books.jagatgururampalji.org/geeta-tera-gyan-amrit',
    pdfUrl: 'https://www.jagatgururampalji.org/gita_tera_gyan_amrit_full.pdf',
    category: 'सद्ग्रंथ मीमांसा',
    categoryEn: 'Scripture Hermeneutics',
    language: 'हिन्दी',
    featured: true,
  },
  {
    id: 'andh-shradha-bhakti',
    title: 'अंध श्रद्धा भक्ति - खतरा-ए-जान',
    titleEn: 'Blind Faith - Danger to Life',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/andh-shradha.webp',
    description: 'शास्त्र विरुद्ध साधना, ढोंग और पाखंडों से सावधान कर सत्य शास्त्रों पर आधारित साधना से परिचित कराने वाली शोधपरक पुस्तक।',
    descriptionEn: 'A research-based expose on unscriptural rituals, warning humanity against blind dogmas and guiding towards scriptural worship.',
    readUrl: 'https://books.jagatgururampalji.org/andh-shraddha-bhakti-khatra-e-jaan',
    pdfUrl: 'https://www.jagatgururampalji.org/andh_shradha_khatra_e_jaan.pdf',
    category: 'शास्त्र प्रमाण व विवेक',
    categoryEn: 'Scripture Proofs & Wisdom',
    language: 'हिन्दी',
    featured: true,
  },
  {
    id: 'mukti-bodh',
    title: 'मुक्ति बोध',
    titleEn: 'Mukti Bodh',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/mukti-bodh-hindi.webp',
    description: 'कबीर साहेब की अमर अमृतवाणी की सरल व विशद व्याख्या, जो आत्मा को परमात्मा से मिलने का सीधा मार्ग दर्शाती है।',
    descriptionEn: 'Lucid and profound exposition of Kabir Sahib’s eternal nectar verses leading souls to direct divine liberation.',
    readUrl: 'https://books.jagatgururampalji.org/mukti-bodh',
    pdfUrl: 'https://www.jagatgururampalji.org/mukti_bodh_full.pdf',
    category: 'अमृतवाणी व्याख्या',
    categoryEn: 'Sacred Verse Commentary',
    language: 'हिन्दी',
    featured: false,
  },
  {
    id: 'garima-gita-ki',
    title: 'गरिमा गीता की',
    titleEn: 'Garima Gita Ki',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/garima-gita-ki-hindi.webp',
    description: 'गीता जी के 18 अध्यायों का निष्पक्ष, तत्वदर्शी और सर्वसुलभ विश्लेषण।',
    descriptionEn: 'Impartial, enlightened, and universally accessible examination of all 18 chapters of the Gita.',
    readUrl: 'https://books.jagatgururampalji.org/garima-geeta-ki-hindi',
    pdfUrl: 'https://www.jagatgururampalji.org/garima_geeta_ki.pdf',
    category: 'सद्ग्रंथ मीमांसा',
    categoryEn: 'Scripture Hermeneutics',
    language: 'हिन्दी',
    featured: false,
  },
  {
    id: 'muslim-nahi-samjhe-gyan-quran',
    title: 'मुसलमान नहीं समझे ज्ञान क़ुरआन',
    titleEn: 'The Real Message of Quran',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/muslim-nahi-samjhe-gyan-quran-hindi.webp',
    description: 'पवित्र क़ुरआन शरीफ़ की सूरतों और आयतों के यथार्थ अर्थों का ऐतिहासिक व आध्यात्मिक विश्लेषण।',
    descriptionEn: 'Historical and spiritual analysis of the verses of the Holy Quran pointing to supreme compassion.',
    readUrl: 'https://books.jagatgururampalji.org/muslim-nahi-samjhe-gyan-quran',
    pdfUrl: 'https://www.jagatgururampalji.org/muslim_nahi_samjhe_gyan_quran_hindi.pdf',
    category: 'सद्ग्रंथ मीमांसा',
    categoryEn: 'Scripture Hermeneutics',
    language: 'हिन्दी',
    featured: false,
  },
  {
    id: 'bhakti-se-bhagwan-tak',
    title: 'भक्ति से भगवान तक',
    titleEn: 'From Devotion to God',
    coverImage: 'https://www.jagatgururampalji.org/img/publications/bhakti-se-bhagwan-tak-hindi.webp',
    description: 'मनुष्य जन्म के मूल उद्देश्य, गुरु की अनिवार्यता और सच्ची साधना का सर्वांगीण परिचय।',
    descriptionEn: 'Comprehensive discourse on the purpose of human life, necessity of a true Guru, and right devotion.',
    readUrl: 'https://books.jagatgururampalji.org/bhakti-se-bhagwan-tak',
    pdfUrl: 'https://www.jagatgururampalji.org/bhakti_se_bhagwan_tak_hindi.pdf',
    category: 'साधना विधि',
    categoryEn: 'Spiritual Discipline',
    language: 'हिन्दी',
    featured: false,
  },
];

// Regular video library: STRICTLY from Factful Debates, Annapurna Muhim Official, and SA True Story Official
export const VIDEOS_DATA: VideoItem[] = [
  {
    id: 'fd-1',
    title: 'पवित्र वेदों और गीता में पूर्ण परमात्मा का प्रमाण - ऐतिहासिक शोध',
    titleEn: 'Evidence of Supreme God in Vedas and Gita - Historical Research',
    thumbnail: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    youtubeUrl: 'https://www.youtube.com/@FactfulDebates',
    channel: 'Factful Debates',
    videoId: 'fd_vedas_gita_proof',
  },
  {
    id: 'am-1',
    title: 'अन्नपूर्णा मुहिम: दूरस्थ गांवों में असहाय और लाचार परिवारों तक राशन सेवा',
    titleEn: 'Annapurna Mission: Ration Delivery to Underprivileged Families in Remote Villages',
    thumbnail: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&auto=format&fit=crop&q=80',
    youtubeUrl: 'https://www.youtube.com/@AnnapurnaMuhimofficial',
    channel: 'Annapurna Muhim Official',
    videoId: 'am_rural_outreach',
  },
  {
    id: 'sa-1',
    title: 'नास्त्रेदमस की भविष्यवाणी: भारत से वह महान तत्वदर्शी संत कौन है?',
    titleEn: 'Nostradamus Prophecy: Who is the Great Tatvdarshi Saint from India?',
    thumbnail: 'https://images.unsplash.com/photo-1532012164546-f432f2e3edd4?w=600&auto=format&fit=crop&q=80',
    youtubeUrl: 'https://www.youtube.com/@SATrueStoryOfficial/videos',
    channel: 'SA True Story Official',
    videoId: 'sa_nostradamus_prophecy',
  },
  {
    id: 'fd-2',
    title: 'तत्वज्ञान बनाम पाखंड: क्यों आवश्यक है शास्त्रसम्मत भक्ति?',
    titleEn: 'Spiritual Truth vs Blind Dogma: Why Scripture-Based Worship is Essential',
    thumbnail: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=600&auto=format&fit=crop&q=80',
    youtubeUrl: 'https://www.youtube.com/@FactfulDebates',
    channel: 'Factful Debates',
    videoId: 'fd_truth_vs_dogma',
  },
  {
    id: 'am-2',
    title: 'अन्नपूर्णा मुहिम: बेघर दिव्यांग वृद्ध दंपति के लिए पक्के मकान का निर्माण',
    titleEn: 'Annapurna Mission: Building a Permanent House for an Impoverished Elderly Couple',
    thumbnail: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600&auto=format&fit=crop&q=80',
    youtubeUrl: 'https://www.youtube.com/@AnnapurnaMuhimofficial',
    channel: 'Annapurna Muhim Official',
    videoId: 'am_shelter_construction',
  },
  {
    id: 'sa-2',
    title: '17 मिनट में दहेज मुक्त विवाह: भारत में सामाजिक क्रांति की सच्ची दास्तान',
    titleEn: '17-Minute Dowry-Free Marriage: The True Story of India’s Social Revolution',
    thumbnail: 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=600&auto=format&fit=crop&q=80',
    youtubeUrl: 'https://www.youtube.com/@SATrueStoryOfficial/videos',
    channel: 'SA True Story Official',
    videoId: 'sa_dowry_free_marriage',
  },
];

// EXACT User-Supplied YouTube Video + Playlist + Show Sources
export const FEATURED_MEDIA_ITEMS: FeaturedMediaItem[] = [
  {
    id: 'pl-sa-true-story',
    type: 'playlist',
    title: 'आत्महत्या का समाधान। अब कोई नहीं करेगा आत्महत्या | SA True Story | Shilya, Sundargarh (OR)',
    titleEn: 'Solution to Suicide | SA True Story Official Playlist',
    thumbnail: 'https://i.ytimg.com/vi/J9vqqiEwApc/hqdefault.jpg',
    url: 'https://www.youtube.com/watch?v=J9vqqiEwApc&list=PL9xnADcE4fNcxxvpeGg2Rm_iVn5UYVvl0',
    channel: 'SA True Story',
    videoId: 'J9vqqiEwApc',
    badge: 'प्लेलिस्ट',
    badgeEn: 'Playlist',
  },
  {
    id: 'vid-qx4tr',
    type: 'video',
    title: 'धरती पर अवतार || Incarnation on Earth || कलयुग में सतयुग की शुरुआत भाग - 8 || Factful Debates',
    titleEn: 'Incarnation on Earth | Kalyug me Satyug ki Shuruat Part 8 | Factful Debates',
    thumbnail: 'https://i.ytimg.com/vi/Qx4trBDBH9k/hqdefault.jpg',
    url: 'https://youtu.be/Qx4trBDBH9k',
    channel: 'Factful Debates',
    videoId: 'Qx4trBDBH9k',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-couwk',
    type: 'video',
    title: 'Kalki Avatar || Manoj Gupta के बिगड़े बोल - अब खुलेगी पोल | Saviour Of The World || Sant Rampal Ji',
    titleEn: 'Kalki Avatar || Manoj Gupta Exposed | Saviour Of The World || Sant Rampal Ji',
    thumbnail: 'https://i.ytimg.com/vi/CoUWK489P9M/hqdefault.jpg',
    url: 'https://youtu.be/CoUWK489P9M',
    channel: 'Factful Debates',
    videoId: 'CoUWK489P9M',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-wzaro',
    type: 'video',
    title: 'भारत ऐसे बनेगा सोने की चिड़िया - Complete Roadmap | कलयुग में सतयुग की शुरुआत भाग 7 Factful Debates',
    titleEn: 'India as Golden Bird - Complete Roadmap | Kalyug me Satyug Part 7',
    thumbnail: 'https://i.ytimg.com/vi/wZARO887gn0/hqdefault.jpg',
    url: 'https://youtu.be/wZARO887gn0',
    channel: 'Factful Debates',
    videoId: 'wZARO887gn0',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-sjsjg',
    type: 'video',
    title: 'Trailer | सनातनी पूजा के पतन की कहानी, संत रामपाल जी महाराज की जुबानी | Part-6 | गोवर्धन पूजा',
    titleEn: 'Trailer | Story of the Decline of Sanatani Worship by Sant Rampal Ji Maharaj | Part 6',
    thumbnail: 'https://i.ytimg.com/vi/SJsJGFZkMIQ/hqdefault.jpg',
    url: 'https://youtu.be/SJsJGFZkMIQ',
    channel: 'Factful Debates',
    videoId: 'SJsJGFZkMIQ',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-utzgm',
    type: 'video',
    title: 'Official Trailer | डॉ. भीमराव अंबेडकर जी की बड़ी भूल | Part - 2 | Factful Debates',
    titleEn: 'Official Trailer | Dr. Bhimrao Ambedkar Ji Analysis | Part 2 | Factful Debates',
    thumbnail: 'https://i.ytimg.com/vi/uTZGMAP7OhM/hqdefault.jpg',
    url: 'https://youtu.be/uTZGMAP7OhM',
    channel: 'Factful Debates',
    videoId: 'uTZGMAP7OhM',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-hpxhv',
    type: 'video',
    title: 'Trailer: 16 महाकला और परकाया प्रवेश का रहस्य | भविष्य मालिका में कल्कि की पहचान | 14 मार्च 2026',
    titleEn: 'Trailer: Mystery of 16 Mahakala and Parakaya Pravesh | Bhavishya Malika Kalki Revelation',
    thumbnail: 'https://i.ytimg.com/vi/HpXHvismlB8/hqdefault.jpg',
    url: 'https://youtu.be/HpXHvismlB8',
    channel: 'Factful Debates',
    videoId: 'HpXHvismlB8',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-sfunv',
    type: 'video',
    title: 'Teaser: कलयुग में सतयुग की शुरुआत भाग - 5 || Factful Debates',
    titleEn: 'Teaser: Kalyug me Satyug ki Shuruat Part 5 || Factful Debates',
    thumbnail: 'https://i.ytimg.com/vi/sfUnVTKzA3A/hqdefault.jpg',
    url: 'https://youtu.be/sfUnVTKzA3A',
    channel: 'Factful Debates',
    videoId: 'sfUnVTKzA3A',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'vid-x3cpj',
    type: 'video',
    title: 'दुनिया वालों सुन लो बात पते की | Sant Rampal Ji Maharaj का सम्पूर्ण जीवन चरित्र || Factful Debates',
    titleEn: 'Sant Rampal Ji Maharaj Complete Life Biography || Factful Debates',
    thumbnail: 'https://i.ytimg.com/vi/X3CpjUkXo9Y/hqdefault.jpg',
    url: 'https://youtu.be/X3CpjUkXo9Y',
    channel: 'Factful Debates',
    videoId: 'X3CpjUkXo9Y',
    badge: 'वीडियो',
    badgeEn: 'Video',
  },
  {
    id: 'show-kalyug',
    type: 'show',
    title: 'कलयुग में सतयुग की शुरुआत (YouTube Show)',
    titleEn: 'Beginning of Satyug in Kalyug (Official YouTube Show)',
    thumbnail: 'https://i.ytimg.com/vi/t-aTJWdMEvQ/hqdefault.jpg',
    url: 'https://www.youtube.com/show/VLPLci4PS0qbjkw?sbp=Kgt0LWFldkTUV2UUAB',
    channel: 'Factful Debates',
    badge: 'यूट्यूब शो',
    badgeEn: 'YouTube Show',
  },
];

// Annapurna Muhim Field Outreach Photos (annapurnamuhim.com & verified initiatives)
export const ANNAPURNA_PHOTOS: PhotoItem[] = [
  {
    id: 'p2',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Feeding-the-hunger.webp',
    title: 'अन्नपूर्णा मुहिम - घर-घर निःशुल्क राशन वितरण',
    titleEn: 'Annapurna Mission - Door-to-Door Free Ration Delivery',
    category: 'अन्नपूर्णा मुहिम',
    source: 'annapurna-website',
    caption: 'असहाय परिवारों तक जीवन रक्षक खाद्य सामग्री की आपूर्ति',
    captionEn: 'Supplying essential food kits directly to helpless families',
    instagramAccount: '@annapurnamuhim',
    postUrl: 'https://www.instagram.com/annapurnamuhim/',
    aspectRatio: 'wide',
  },
  {
    id: 'p-ig-am-1',
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80',
    title: 'अन्नपूर्णा आवास निर्माण: बेसहारा परिवार को पक्का मकान',
    titleEn: 'Annapurna Shelter Project: Brick House for Destitute Family',
    category: 'अन्नपूर्णा मुहिम',
    source: 'instagram',
    caption: 'Instagram @annapurnamuhim से प्रकाशित नवीन आवास निर्माण कार्य',
    captionEn: 'Newly constructed concrete home featured on @annapurnamuhim',
    instagramAccount: '@annapurnamuhim',
    postUrl: 'https://www.instagram.com/annapurnamuhim/',
    aspectRatio: 'tall',
  },
  {
    id: 'p-ig-am-2',
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
    title: 'दूरस्थ गांवों में राशन एवं शीतकालीन राहत वितरण',
    titleEn: 'Remote Village Ration & Winter Warmth Outreach',
    category: 'अन्नपूर्णा मुहिम',
    source: 'instagram',
    caption: 'Instagram @annapurnamuhim से सत्यापित मानवीय सेवा झलकियां',
    captionEn: 'Verified humanitarian service glimpses via @annapurnamuhim',
    instagramAccount: '@annapurnamuhim',
    postUrl: 'https://www.instagram.com/annapurnamuhim/',
    aspectRatio: 'wide',
  },
  {
    id: 'p-ig-am-3',
    image: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80',
    title: 'बाढ़ राहत महाभियान: खेतों व गांवों से जल निकासी',
    titleEn: 'Flood Rescue Mission: Farmland Drainage Operations',
    category: 'अन्नपूर्णा मुहिम',
    source: 'instagram',
    caption: 'Instagram @annapurnamuhim द्वारा संकलित बाढ़ राहत प्रयास',
    captionEn: 'Flood evacuation and water drainage captured on @annapurnamuhim',
    instagramAccount: '@annapurnamuhim',
    postUrl: 'https://www.instagram.com/annapurnamuhim/',
    aspectRatio: 'square',
  },
  {
    id: 'p-ig-am-4',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    title: 'शिक्षा सहयोग: जरूरतमंद विद्यार्थियों को पुस्तकें व किट',
    titleEn: 'Education Aid: Free Books & Kits for Impoverished Students',
    category: 'अन्नपूर्णा मुहिम',
    source: 'annapurna-website',
    caption: 'annapurnamuhim.com अंतर्गत गरीब बच्चों की शिक्षा की जिम्मेदारी',
    captionEn: 'Educational sponsorship under annapurnamuhim.com',
    instagramAccount: '@annapurnamuhim',
    postUrl: 'https://www.instagram.com/annapurnamuhim/',
    aspectRatio: 'tall',
  },
];

// Annapurna Muhim Core Initiatives from https://annapurnamuhim.com/
export const ANNAPURNA_INITIATIVES: AnnapurnaInitiative[] = [
  {
    id: 'food-support',
    title: 'रोटी एवं राशन सहायता',
    titleEn: 'Food & Monthly Ration Support',
    icon: 'Utensils',
    tagline: 'कोई भूखा न सोए • घर-घर मासिक राशन किट',
    taglineEn: 'No One Sleeps Hungry • Monthly Ration Kits at Doorstep',
    description: 'ऐसे दिव्यांग, बुजुर्ग अथवा अनाथ परिवार जिनके पास आजीविका का साधन नहीं है, उन्हें आटा, चावल, दालें, शुद्ध तेल, मसाले और नमक सहित संपूर्ण राशन किट हर महीने सीधे घर पहुंचाई जाती है।',
    descriptionEn: 'Delivering comprehensive monthly food kits (flour, rice, pulses, cooking oil, spices) directly to elderly, orphaned, and disabled families with zero livelihood.',
    points: [
      'नियमित मासिक राशन आपूर्ति ताकि कोई भूखा न सोए',
      'राशन समाप्ति से पूर्व सूचना हेतु सहायता संपर्क कार्ड',
      'बिना किसी आवेदन या औपचारिक कागजी झंझट के प्रत्यक्ष सत्यापन',
    ],
    pointsEn: [
      'Consistent monthly replenishment ensuring nutritional dignity',
      'Direct helpline contact card provided with every kit',
      'Direct volunteer home verification with no cumbersome paperwork',
    ],
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Feeding-the-hunger.webp',
    source: 'annapurna-website',
    link: 'https://annapurnamuhim.com/',
  },
  {
    id: 'clothing',
    title: 'वस्त्र वितरण सेवा',
    titleEn: 'Clothing & Winter Relief',
    icon: 'Shirt',
    tagline: 'सम्मानजनक जीवन हेतु वस्त्र एवं शीतकालीन कंबल',
    taglineEn: 'Dignified Living • Seasonal Clothing & Warm Blankets',
    description: 'गरीब और असहाय परिवारों, झोपड़पट्टियों और फुटपाथों पर रहने वाले लोगों को नए कपड़े, गर्म शॉल, स्वेटर और सर्दियों में मोटे कंबल वितरित किए जाते हैं।',
    descriptionEn: 'Providing clean clothing, warm sweaters, and heavy thermal blankets during harsh winters to homeless and underprivileged families.',
    points: [
      'कड़कड़ाती ठंड में कंबल एवं गर्म कपड़ों का तत्काल वितरण',
      'बच्चों और वृद्धों के लिए विशेष आवरण व पोशाकें',
      'पूर्णतः निःशुल्क एवं सम्मानजनक वितरण',
    ],
    pointsEn: [
      'Immediate winter drives providing thick blankets and warm clothes',
      'Tailored clothing support for children and elderly individuals',
      '100% free and respectful distribution',
    ],
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=700&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    link: 'https://annapurnamuhim.com/',
  },
  {
    id: 'housing',
    title: 'आवास सहायता (पक्के मकान)',
    titleEn: 'Permanent Housing & Shelter Aid',
    icon: 'Home',
    tagline: 'टूटी झोपड़ियों की जगह पक्के व सुरक्षित घर',
    taglineEn: 'Replacing Crumbling Shacks with Permanent Brick Homes',
    description: 'बरसात और आंधी में ढहने की कगार पर खड़ी कच्ची झोपड़ियों में रहने वाले निराश्रित परिवारों के लिए पक्के कमरों, छत और शौचालयों का निर्माण करवाया जाता है।',
    descriptionEn: 'Constructing sturdy brick-and-mortar rooms, weather-proof roofs, and sanitary facilities for destitute families living in dilapidated shacks.',
    points: [
      'करावल नगर (दिल्ली), रोहतक (हरियाणा) सहित दर्जनों स्थानों पर घर निर्माण',
      'बारिश व धूप से सुरक्षित छत और दरवाजे-खिड़कियां',
      'सामग्री व निर्माण कार्य का संपूर्ण व्यय मिशन द्वारा वहन',
    ],
    pointsEn: [
      'Homes built across Karawal Nagar (Delhi), Rohtak (Haryana), and rural areas',
      'Weather-tight concrete roofs, secure doors, and proper sanitation',
      '100% of construction and raw material costs borne by the mission',
    ],
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=700&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    link: 'https://annapurnamuhim.com/',
  },
  {
    id: 'education',
    title: 'शिक्षा सहयोग',
    titleEn: 'Educational Assistance',
    icon: 'GraduationCap',
    tagline: 'आर्थिक तंगी से कोई बच्चा स्कूल न छोड़े',
    taglineEn: 'Ensuring No Child Drops Out Due to Financial Distress',
    description: 'अनाथ अथवा निर्धन परिवारों के बच्चों की स्कूल फीस, यूनिफॉर्म, कॉपियां, किताबें और स्कूल बैग की व्यवस्था कर उन्हें शिक्षा से जोड़े रखना।',
    descriptionEn: 'Sponsoring school fees, textbooks, stationery, uniforms, and bags so impoverished children never drop out of school.',
    points: [
      'जरूरतमंद विद्यार्थियों की वार्षिक व मासिक स्कूल फीस का भुगतान',
      'शैक्षणिक सामग्री, बैग और स्कूल यूनिफॉर्म का वितरण',
      'बालिकाओं की शिक्षा को विशेष प्राथमिकता',
    ],
    pointsEn: [
      'Direct payment of school and examination fees for underprivileged students',
      'Provision of school bags, stationery notebooks, and mandatory uniforms',
      'Dedicated focus on girl child education',
    ],
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=700&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    link: 'https://annapurnamuhim.com/',
  },
  {
    id: 'medical',
    title: 'चिकित्सा सहायता',
    titleEn: 'Medical Aid & Healthcare Support',
    icon: 'Stethoscope',
    tagline: 'बीमारों को दवाइयां, उपचार व व्हीलचेयर सहायता',
    taglineEn: 'Medicines, Treatment Expenses & Wheelchairs for the Sick',
    description: 'लाचार बीमारों, वृद्धों और दिव्यांगों के लिए जरूरी दवाइयों की मासिक व्यवस्था, अस्पतालों में जांच और जरूरतमंदों को व्हीलचेयर व बैसाखियां उपलब्ध कराना।',
    descriptionEn: 'Arranging vital monthly medicines, hospital diagnosis support, and mobility equipment (wheelchairs, crutches) for disabled and bedridden individuals.',
    points: [
      'गंभीर रूप से बीमार असहायों के लिए नियमित दवाइयों की किट',
      'दिव्यांगों को ट्राइसाइकिल एवं व्हीलचेयर प्रदान करना',
      'दवाइयों के अभाव में किसी की जान न जाए, यह सुनिश्चित करना',
    ],
    pointsEn: [
      'Regular monthly provision of prescribed medicines for chronically ill patients',
      'Distribution of wheelchairs and mobility tricycles for disabled beneficiaries',
      'Zero commercial motivation; pure humanitarian relief',
    ],
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=700&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    link: 'https://annapurnamuhim.com/',
  },
  {
    id: 'flood-relief',
    title: 'बाढ़ राहत महाभियान',
    titleEn: 'Disaster & Flood Relief Operations',
    icon: 'Waves',
    tagline: 'हरियाणा, पंजाब, राजस्थान व उत्तराखंड में आपदा सेवा',
    taglineEn: 'Relief in Haryana, Punjab, Rajasthan, HP, Uttarakhand & Delhi',
    description: 'बाढ़ प्रभावित क्षेत्रों में जलभराव से डूबे खेतों व गांवों से पानी निकालने के लिए हाई-पावर मोटरें, लंबे पाइप और भोजन पैकेट भेजकर किसानों और ग्रामीणों की रक्षा की।',
    descriptionEn: 'Deploying high-power water evacuation pumps, industrial drainage pipes, and emergency food packets to rescue flood-hit farmers and villages.',
    points: [
      'हजारों एकड़ डूबी कृषि भूमि से पानी निकालकर किसानों की फसलें बचाईं',
      'बाढ़ से घिरे परिवारों तक नावों और सेवादारों द्वारा भोजन व पेयजल',
      'बाढ़ पश्चात बीमारियों की रोकथाम हेतु राहत सामग्री',
    ],
    pointsEn: [
      'Draining thousands of submerged farmland acres to safeguard livelihoods',
      'Boat-assisted emergency food and potable drinking water distribution',
      'Post-flood hygiene assistance and dry ration replenishment',
    ],
    image: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=700&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    link: 'https://annapurnamuhim.com/',
  },
];

// Latest Stories / Articles from https://annapurnamuhim.com/
export const ANNAPURNA_STORIES: AnnapurnaStory[] = [
  {
    id: 'as-1',
    title: 'रोहतक के गांव में बेसहारा वृद्ध दंपति को मिला पक्का आशियाना',
    titleEn: 'Destitute Elderly Couple in Rohtak Village Receives Permanent Brick House',
    date: '14 सितम्बर 2026',
    dateEn: 'September 14, 2026',
    image: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=800&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    description: 'बरसात में गिर चुकी कच्ची झोपड़ी में रह रहे बुजुर्ग दंपति को अन्नपूर्णा मुहिम के सेवादारों ने कुछ ही हफ्तों में मजबूत पक्का कमरा, रसोई व शौचालय बनाकर सौंपा।',
    descriptionEn: 'Volunteers built and handed over a strong brick room with weather-resistant roof and toilet to an elderly couple whose dilapidated shack had collapsed.',
    articleUrl: 'https://annapurnamuhim.com/',
    category: 'आवास सहायता',
    categoryEn: 'Shelter Aid',
  },
  {
    id: 'as-2',
    title: 'तमिलनाडु और तेलंगाना के सुदूर गांवों में 3200+ परिवारों तक राशन किट',
    titleEn: 'Monthly Ration Kits Delivered to 3200+ Impoverished Families in South India',
    date: '10 सितम्बर 2026',
    dateEn: 'September 10, 2026',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Feeding-the-hunger.webp',
    source: 'annapurna-website',
    description: 'अन्नपूर्णा मुहिम की टीम ने भाषाई और भौगोलिक सीमाओं से परे जाकर दक्षिण भारत के दूरस्थ गांवों में असहाय बुजुर्गों व दिव्यांगों के घर-घर राशन पहुंचाया।',
    descriptionEn: 'Transcending geographical and linguistic barriers, Annapurna teams delivered wholesome monthly ration kits to disabled and elderly families.',
    articleUrl: 'https://annapurnamuhim.com/',
    category: 'राशन सेवा',
    categoryEn: 'Ration Support',
  },
  {
    id: 'as-3',
    title: 'बाढ़ पीड़ित किसानों के खेतों से जल निकासी: हजारों एकड़ फसल सुरक्षित',
    titleEn: 'Flood Drainage Rescue: Saving Thousands of Acres of Submerged Farmland',
    date: '02 सितम्बर 2026',
    dateEn: 'September 02, 2026',
    image: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=800&auto=format&fit=crop&q=80',
    source: 'annapurna-website',
    description: 'अत्यधिक बारिश से जलमग्न खेतों में अन्नपूर्णा मुहिम ने भारी क्षमता वाली मोटरें और पाइपलाइन स्थापित कर किसानों की खड़ी फसल को सड़ने से बचाया।',
    descriptionEn: 'Installing heavy-capacity drainage motors and pipelines free of cost, saving farmers from catastrophic financial and crop ruin.',
    articleUrl: 'https://annapurnamuhim.com/',
    category: 'बाढ़ राहत',
    categoryEn: 'Flood Relief',
  },
];

// Spiritual Topics
export const SPIRITUAL_TOPICS: SpiritualTopic[] = [
  {
    id: 'sacchi-bhakti',
    title: 'सच्ची भक्ति का मार्ग',
    titleEn: 'The Path of True Devotion',
    subtitle: 'शास्त्रसम्मत साधना और लोकवेद आधारित पाखंडों का अंत',
    subtitleEn: 'Scriptural Devotion and End of Unscriptural Traditions',
    description: 'श्रीमद्भगवद्गीता अध्याय 16 श्लोक 23 में स्पष्ट कहा गया है कि जो मनुष्य शास्त्रविधि को त्यागकर मनमाना आचरण करता है, वह न तो सुख पाता है और न ही मुक्ति।',
    descriptionEn: 'Gita Chapter 16 Verse 23 declares that one who abandons scriptural injunctions and acts on whimsical desires attains neither happiness nor salvation.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/creation-nature/creation-of-nature.webp',
    details: 'वर्तमान में अधिकांश समाज गुरु विहीन अथवा शास्त्र विरुद्ध पूजाओं (तीर्थ, व्रत, पिंड दान, कब्र पूजा आदि) में फंसा हुआ है। तत्वदर्शी संत रामपाल जी महाराज सर्व धर्मों के पवित्र ग्रंथों को खोलकर वास्तविक शास्त्रसम्मत साधना प्रदान करते हैं।',
    detailsEn: 'Most people are trapped in unscriptural rites without a true Guru. Tatvdarshi Sant Rampal Ji Maharaj opens authentic scriptures to reveal the true scriptural discipline.',
    references: ['श्रीमद्भगवद्गीता 16:23-24', 'यजुर्वेद अध्याय 40 मन्त्र 8', 'कबीर साहेब की अमृतवाणी'],
  },
  {
    id: 'srishti-rachna',
    title: 'सृष्टि रचना का यथार्थ रहस्य',
    titleEn: 'The Reality of Creation of Nature',
    subtitle: 'किसने की सम्पूर्ण ब्रह्मांड और लोकों की रचना?',
    subtitleEn: 'Who Created the Entire Universe and All Realms?',
    description: 'पूर्ण परमेश्वर कबीर साहेब ने अपने संकल्प मात्र से अमर सतलोक, अलख लोक, अगम लोक और अनामी लोक की रचना की।',
    descriptionEn: 'Supreme God Kabir created the immortal realms (Satlok, Alakh Lok, Agam Lok, and Anami Lok) by His divine supreme will.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/kaal.webp',
    details: 'ऋग्वेद मण्डल 10 सूक्त 90 मन्त्र 1-5 तथा गीता अध्याय 15 श्लोक 1-4 में उल्टे लटके हुए संसार रूपी वृक्ष का वर्णन है। पूर्ण परमात्मा कबीर साहेब ही सर्व लोकों के धारक व पालक हैं।',
    detailsEn: 'Rigveda Mandala 10 Sukta 90 and Gita Chapter 15 Verses 1-4 describe the cosmic inverted tree. Supreme God Kabir is the sole creator and sustainer of all worlds.',
    references: ['ऋग्वेद मण्डल 10 सूक्त 90', 'गीता अध्याय 15 श्लोक 1-4', 'कबीर सागर - अनुराग सागर'],
  },
  {
    id: 'kalyug-mein-satyug',
    title: 'कलयुग में सतयुग',
    titleEn: 'Golden Age in Kaliyuga',
    subtitle: 'सत्य ज्ञान से नैतिक व आध्यात्मिक क्रांति',
    subtitleEn: 'Moral and Spiritual Revolution through Divine Truth',
    description: 'जब जन-जन सत्य साधना अपनाकर चोरी, रिश्वत, ठगी, नशा और ईर्ष्या का त्याग करता है, तो इसी धरती पर सतयुग जैसी दिव्य मर्यादाएं स्थापित होती हैं।',
    descriptionEn: 'When people embrace true worship and renounce theft, bribery, addiction, and malice, righteous Golden Age values reign supreme on Earth.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/social-reforms-1.webp',
    details: 'संत रामपाल जी महाराज के करोड़ों अनुयायी किसी भी प्रकार का नशा नहीं करते, रिश्वत नहीं लेते, दहेज नहीं लेते और न देते हैं। इस प्रकार समाज में सत्य, प्रेम और भाईचारे का सतयुगी वातावरण बन चुका है।',
    detailsEn: 'Millions of followers neither accept nor give dowry, abstain completely from all intoxicants and corruption, creating an atmosphere of eternal harmony.',
    references: ['सद्ग्रंथ प्रमाण', 'नास्त्रेदमस भविष्यवाणी (Century 1, Q.50)', 'विश्व शांति संदेश'],
  },
  {
    id: 'mukti-ka-marg',
    title: 'मुक्ति का मार्ग',
    titleEn: 'The Path to Salvation',
    subtitle: 'जन्म-मरण के बंधन से छूटकर अमर सतलोक गमन',
    subtitleEn: 'Breaking Free from the Cycle of Birth & Death to Attain Satlok',
    description: 'यह चौरासी लाख योनियों का चक्रव्यूह केवल सच्चे गुरु की शरण में मर्यादित रहकर शास्त्रानुकूल सुमिरन करने से ही समाप्त हो सकता है।',
    descriptionEn: 'The endless trap of 8.4 million life-forms can only be permanently shattered through disciplined remembrance guided by an enlightened Saint.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/about-guruji.webp',
    details: 'गीता अध्याय 8 श्लोक 16 में कहा है कि ब्रह्मलोक तक के सभी लोक पुनरावर्ती हैं (जीव लौटकर जन्म-मरण में आता है)। परंतु उस परम अव्यक्त परम धाम (सतलोक) को प्राप्त होने पर जीव कभी संसार में वापस नहीं आता।',
    detailsEn: 'Gita Chapter 8 Verse 16 states that all realms up to Brahmaloka are cyclical. Reaching the supreme immortal realm of Satlok guarantees eternal freedom.',
    references: ['गीता अध्याय 8 श्लोक 16 व 20-21', 'यजुर्वेद अध्याय 8 मन्त्र 13', 'ऋग्वेद मण्डल 9 सूक्त 96'],
  },
];

// Holy Scriptures
export const HOLY_SCRIPTURES: HolyScripture[] = [
  {
    id: 'gita',
    name: 'पवित्र श्रीमद्भगवद्गीता',
    nameEn: 'Holy Shrimad Bhagavad Gita',
    title: 'तत्वदर्शी संत एवं पूर्ण परमात्मा का निर्देश',
    titleEn: 'Direct Injunction for Tatvdarshi Saint & Supreme God',
    reference: 'अध्याय 4 श्लोक 34, अध्याय 15 श्लोक 1-4, अध्याय 18 श्लोक 62',
    referenceEn: 'Chapter 4 Verse 34, Chapter 15 Verses 1-4, Chapter 18 Verse 62',
    quote: 'तद्विद्धि प्रणिपातेन परिप्रश्नेन सेवया। उपदेक्ष्यन्ति ते ज्ञानं ज्ञानिनस्तत्त्वदर्शिनः॥',
    meaning: 'उस परम ज्ञान को तत्वदर्शी संतों के पास जाकर समझ। उनको भली-भांति दण्डवत प्रणाम करने से, सेवा करने से और निष्कपट भाव से प्रश्न करने से वे ज्ञानी महापुरुष तुझे तत्वज्ञान का उपदेश करेंगे।',
    meaningEn: 'Understand that true spiritual knowledge by approaching enlightened Tatvdarshi saints. By offering prostrations, service, and humble inquiries, they will impart the truth.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/creation-nature/Hinduism.webp',
  },
  {
    id: 'vedas',
    name: 'पवित्र चारों वेद',
    nameEn: 'The Four Holy Vedas',
    title: 'कविर्देव (कबीर साहेब) ही सर्वशक्तिमान सृष्टिकर्ता',
    titleEn: 'KavirDev (Kabir Sahib) is the Almighty Creator',
    reference: 'ऋग्वेद मण्डल 9 सूक्त 96 मन्त्र 16-20, यजुर्वेद अध्याय 29 मन्त्र 25',
    referenceEn: 'Rigveda Mandala 9 Sukta 96 Verses 16-20, Yajurveda 29:25',
    quote: 'सोमः पवते मतिभिः कवीनां... कविरभिनो अर्कैः।',
    meaning: 'वेद गवाही देते हैं कि सर्वसृष्टि रचनहार, पापों का नाश करने वाला और अमरलोक का अधिपति परमात्मा कविर्देव (कबीर देव) है, जो बाल रूप में भी प्रकट होकर ज्ञान वाणियों का विस्तार करता है।',
    meaningEn: 'The Vedas attest that the creator of all, destroyer of sins, and lord of the eternal realm is Supreme God KavirDev (Kabir), who expands divine truth through sacred speech.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/birth-brahma-vishnu-shiv.webp',
  },
  {
    id: 'guru-granth-sahib',
    name: 'पवित्र श्री गुरु ग्रंथ साहिब',
    nameEn: 'Holy Sri Guru Granth Sahib',
    title: 'हक्का कबीर करीम तू बेऐब परवरदिगार',
    titleEn: 'Hakka Kabir Karim Tu Be-aib Parwardigar',
    reference: 'राग आसा महला 1, राग तिलंग महला 1, राग प्रभाती',
    referenceEn: 'Raag Asa Mehla 1, Raag Tilang Mehla 1, Raag Prabhati',
    quote: 'फाहे काटे मिटे गवन फतह भई मन जीत। कबीर करता आप है दूजा नाही कोइ॥',
    meaning: 'आदरणीय श्री गुरु नानक देव जी ने स्पष्ट स्वीकार किया कि हक्का कबीर करीम तू बेऐब परवरदिगार, जिन्होंने जीव को काल के जाल से छुड़ाकर सतलोक की राह दिखाई।',
    meaningEn: 'Respected Sri Guru Nanak Dev Ji affirmed that Kabir is the flawless Supreme Creator, cutting off worldly traps and granting true liberation.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/creation-nature/Sikhism.webp',
  },
  {
    id: 'quran',
    name: 'पवित्र क़ुरआन शरीफ़',
    nameEn: 'The Holy Quran',
    title: 'अल्लाह कबीर और बाख़बर संत का रहस्य',
    titleEn: 'Allah Kabir & the Enlightened (Bakhabar) Saint',
    reference: 'सूरत अल-फ़ुरक़ान 25, आयत 52 से 59',
    referenceEn: 'Surah Al-Furqan 25, Verses 52 to 59',
    quote: 'व तवक्कल् अलल हय्यिल्लज़ी ला यमूतु... अल्लज़ी ख़लक़स् समावाति वल अर्ज़... अर्रहमानु फ़स्अल बिही ख़बीरा॥',
    meaning: 'उस ज़िन्दा पर भरोसा रखो जो कभी नहीं मरता, जिसने छह दिन में आकाशों, धरती और जो कुछ उनके बीच है पैदा किया और सातवें दिन तख्त पर जा विराजा। वह रहमान (दयालु कबीर) है, उसकी ख़बर किसी बाख़बर (तत्वदर्शी) से पूछो।',
    meaningEn: 'Put trust in the Ever-Living who never dies, who created the heavens and earth in six days and ascended His throne on the seventh. Ask an enlightened one (Bakhabar) about Him.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/creation-nature/Islam.webp',
  },
  {
    id: 'bible',
    name: 'पवित्र बाइबल',
    nameEn: 'The Holy Bible',
    title: 'ईश्वर साकार और मनुष्य रूप में है',
    titleEn: 'God is in Human Form',
    reference: 'उत्पत्ति ग्रन्थ (Genesis) अध्याय 1 आयत 26-27',
    referenceEn: 'Genesis Chapter 1, Verses 26-27',
    quote: 'Then God said, "Let us make mankind in our image, in our likeness..." So God created mankind in his own image.',
    meaning: 'पवित्र बाइबल के आरंभ में ही स्पष्ट लिखा है कि परमात्मा निराकार नहीं अपितु साकार मनुष्य रूप में है, जिसने अपनी ही छवि में मानव की रचना की।',
    meaningEn: 'The Bible clearly reveals from Genesis that God has an eternal visible form and created humankind in His own image and likeness.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/creation-nature/Christianity.webp',
  },
  {
    id: 'puranas',
    name: 'पवित्र पुराण',
    nameEn: 'The Holy Puranas',
    title: 'त्रिगुण एवं त्रिदेवों की उत्पत्ति का साक्ष्य',
    titleEn: 'Genesis of the Three Gunas and Tridevas',
    reference: 'श्रीमद्देवी भागवत, श्रीविष्णु पुराण, शिव महापुराण',
    referenceEn: 'Shrimad Devi Bhagavata, Vishnu Purana, Shiva Purana',
    quote: 'रजोगुण ब्रह्मा, सतोगुण विष्णु, तमोगुण शिव - त्रिगुणात्मिका प्रकृति।',
    meaning: 'पुराणों के यथार्थ अध्ययन से ज्ञात होता है कि ब्रह्मा, विष्णु और शिव जी नाशवान हैं और इनके ऊपर पूर्ण परमेश्वर (कबीर साहेब) अविनाशी प्रभु हैं।',
    meaningEn: 'Puranic scriptures prove that Brahma, Vishnu, and Shiva govern the three qualities and are mortal, while Supreme God Kabir is imperishable.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/three-gunas.webp',
  },
];

// Social Reform Initiatives
export const SOCIAL_REFORMS: SocialReform[] = [
  {
    id: 'intoxication-free',
    title: 'नशा मुक्ति अभियान',
    titleEn: 'Intoxication-Free World',
    tagline: 'लाखों परिवारों का खुशहाल और व्यसनमुक्त जीवन',
    taglineEn: 'Happy, Addiction-Free Lives for Millions of Families',
    description: 'संत रामपाल जी महाराज से नामदीक्षा लेने के बाद प्रत्येक भक्त स्वेच्छा से शराब, बीड़ी, सिगरेट, गुटखा, अफीम, गांजा और मांस-अंडे का आजीवन पूर्ण त्याग करता है।',
    descriptionEn: 'Upon receiving spiritual initiation, every devotee voluntarily and permanently forsakes alcohol, tobacco, narcotics, and non-vegetarian food.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Intoxication-Free-World.webp',
    impactPoints: [
      'करोड़ों लोगों ने बिना किसी दवा या नशा मुक्ति केंद्र के स्वयं नशा छोड़ा',
      'घरेलू कलह, मारपीट और आर्थिक तंगी का स्थायी समाधान',
      'आध्यात्मिक मर्यादा और आत्मबल से प्रेरित स्थायी संयम',
    ],
    impactPointsEn: [
      'Millions voluntarily quit addictions without medical rehab or medications',
      'Permanent elimination of domestic conflict, debt, and poverty',
      'Spiritual restraint anchored in daily prayer and moral discipline',
    ],
  },
  {
    id: 'dowry-free',
    title: 'दहेज मुक्त भारत - 17 मिनट रमैणी विवाह',
    titleEn: 'Dowry-Free India - 17-Minute Ramaini Marriage',
    tagline: 'बिना एक रुपया लेन-देन, बिना किसी दिखावे के विवाह',
    taglineEn: 'Weddings without a Single Rupee Exchange or Extravagance',
    description: 'संत रामपाल जी महाराज के मार्गदर्शन में 17 मिनट में पवित्र गुरुवाणी (असुर निकन्दन रमैणी) के उच्चारण द्वारा पूर्णतः सादगीपूर्ण विवाह सम्पन्न होते हैं।',
    descriptionEn: 'Under the auspices of Sant Rampal Ji Maharaj, marriages are conducted in 17 minutes through the recitation of sacred Asur Nikandan Ramaini without any dowry.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Dowry-free-india.webp',
    impactPoints: [
      'न कोई दहेज, न कोई गहनों-नकदी की मांग',
      'न डीजे, न शराब, न फिजूलखर्ची',
      'कन्या भ्रूण हत्या और बेटियों के बोझ समझे जाने की सोच पर करारी चोट',
    ],
    impactPointsEn: [
      'Zero dowry, zero demand for jewelry, cash, or vehicles',
      'Complete ban on loud DJs, alcohol, and ostentatious feasts',
      'Decisive blow to female foeticide and patriarchal burden stigma',
    ],
  },
  {
    id: 'blood-donation',
    title: 'विशाल रक्तदान एवं चिकित्सा शिविर',
    titleEn: 'Grand Blood Donation & Healthcare Camps',
    tagline: 'मानवता की सेवा ही सबसे बड़ा धर्म',
    taglineEn: 'Selfless Service to Humanity is the Highest Duty',
    description: 'आश्रमों में समय-समय पर लगने वाले विशाल रक्तदान शिविरों में हजारों अनुयायी कतारों में लगकर देश के ब्लड बैंकों के लिए स्वेच्छा से रक्तदान करते हैं।',
    descriptionEn: 'In colossal blood donation drives held across ashrams, thousands of disciplined devotees voluntarily donate pure, unpolluted blood for critical emergency needs.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Blood-donation.webp',
    impactPoints: [
      'एक ही दिन में हजारों यूनिट शुद्ध व नशामुक्त रक्त का संग्रह',
      'सैनिकों, थैलेसीमिया पीड़ितों व आपातकालीन रोगियों हेतु सहायता',
      'जाति, धर्म, संप्रदाय से ऊपर उठकर निष्काम मानव सेवा',
    ],
    impactPointsEn: [
      'Thousands of units of pure, addiction-free blood collected in single days',
      'Crucial lifeline for armed personnel, thalassemia children, and emergency trauma patients',
      'Unbiased humanitarian relief rising above caste, religion, and regional divides',
    ],
  },
  {
    id: 'annapurna-muhim-reform',
    title: 'अन्नपूर्णा मुहिम - भूखमुक्त भारत',
    titleEn: 'Annapurna Mission - Hunger-Free India',
    tagline: 'कोई असहाय या लाचार भूखा न सोए',
    taglineEn: 'Ensuring No Helpless Individual Goes to Bed Hungry',
    description: 'देश के कोने-कोने में बेसहारा, दिव्यांग, अनाथ बच्चों और लाचार बुजुर्गों के घर तक निःशुल्क शुद्ध राशन और भोजन सामग्री पहुंचाना।',
    descriptionEn: 'Door-to-door monthly delivery of wholesome rations and living essentials to destitute, disabled, and orphaned families nationwide.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Feeding-the-hunger.webp',
    impactPoints: [
      'हजारों असहाय परिवारों को प्रतिमाह नियमित राशन सहायता',
      'दूरस्थ गांवों व झोपड़पट्टियों में प्रत्यक्ष पहुंचकर सेवा',
      'बिना किसी राजनीतिक या स्वार्थपूर्ण प्रचार के निरंतर सेवा',
    ],
    impactPointsEn: [
      'Regular monthly ration sustenance delivered to thousands of needy households',
      'Direct doorstep outreach in remote villages, slum settlements, and tribal hamlets',
      'Zero commercial promotion or political motive; pure spiritual compassion',
    ],
  },
  {
    id: 'eliminating-evils',
    title: 'सामाजिक कुरीतियों व अंधविश्वास का खात्मा',
    titleEn: 'Eradication of Social Evils & Superstitions',
    tagline: 'मृत्युभोज, छुआछूत और पाखंडों का समूल नाश',
    taglineEn: 'Uprooting Post-Funeral Feasts, Untouchability & Blind Faith',
    description: 'मृत्युभोज जैसी अमानवीय प्रथा, जातिगत भेदभाव, भूत-प्रेत का भय, टोना-टोटका और अंधविश्वासों को तत्वज्ञान के प्रकाश से समूल समाप्त किया गया है।',
    descriptionEn: 'Eliminating the exploitative burden of death feasts (Mrityu Bhoj), caste untouchability, sorcery fears, and blind rituals through spiritual enlightenment.',
    image: 'https://www.jagatgururampalji.org/theme/alpha-v-1.0-2024/assets/img/social-reforms/Eliminating-Social-Evils.webp',
    impactPoints: [
      'मृत्युभोज पर पूर्ण प्रतिबंध जिससे गरीब कर्ज से बचते हैं',
      'जाति-पाति का भेद मिटाकर एक ही थाली में भोजन का भाव',
      'अंधविश्वासों और तांत्रिक पाखंडों से मुक्ति',
    ],
    impactPointsEn: [
      'Strict ban on death feasts saving poor families from crippling debt traps',
      'Complete eradication of caste discrimination with egalitarian community feasts',
      'Liberation from occult fears, astrology exploitation, and superstitious dogmas',
    ],
  },
];

// Annapurna in Numbers statistics from annapurnamuhim.com
export const ANNAPURNA_STATS = [
  {
    id: 'families',
    value: 3200,
    suffix: '+',
    label: 'मासिक राशन सहायता प्राप्त परिवार',
    labelEn: 'Families Receiving Monthly Ration Kits',
    subtext: 'हर महीने घर-घर शुद्ध आटा, दालें, तेल व नमक की आपूर्ति',
    subtextEn: 'Direct doorstep delivery of nutrition and essentials every month',
  },
  {
    id: 'houses',
    value: 120,
    suffix: '+',
    label: 'निर्मित पक्के सुरक्षित मकान',
    labelEn: 'Permanent Brick Houses Constructed',
    subtext: 'कच्ची टूटी झोपड़ियों की जगह पक्की छत, कमरा व शौचालय',
    subtextEn: 'Replacing dilapidated huts with concrete rooms and sanitation',
  },
  {
    id: 'states',
    value: 14,
    suffix: '+',
    label: 'राज्यों में सक्रिय सेवा अभियान',
    labelEn: 'States with Active Humanitarian Drives',
    subtext: 'तमिलनाडु, तेलंगाना, राजस्थान, हरियाणा, दिल्ली, पंजाब आदि',
    subtextEn: 'Covering Haryana, Delhi, Punjab, Rajasthan, TN, Telangana & more',
  },
  {
    id: 'donations',
    value: 0,
    prefix: '₹',
    suffix: '',
    label: 'स्वीकृत सार्वजनिक दान या चंदा',
    labelEn: 'Public Donations or Funds Accepted',
    subtext: '100% निःशुल्क व निस्वार्थ सेवा - कोई चंदा या दान नहीं',
    subtextEn: '100% Free & Selfless Service - Strictly Zero Public Donation',
  },
];

// Official 8 Annapurna Muhim Ground Seva Videos (Exact YouTube Sources)
export interface AnnapurnaVideoItem {
  id: string;
  videoId: string;
  episode: string;
  title: string;
  titleEn: string;
  location: string;
  locationEn: string;
  thumbnail: string;
  youtubeUrl: string;
  channel: string;
  date: string;
  dateEn: string;
  description: string;
  descriptionEn: string;
}

export const ANNAPURNA_VIDEOS: AnnapurnaVideoItem[] = [
  {
    id: 'annapurna-vid-1',
    videoId: 'YceMS7yuG6k',
    episode: 'EP-3243',
    title: 'EP-3243 | पेरूमबक्कम, कल्लाकुरिची (तमिलनाडु): अन्नपूर्णा मुहिम के तहत मां-बेटे को मिली बड़ी राहत | AnnaPurna Muhim',
    titleEn: 'EP-3243 | Perumbakkam, Kallakurichi (Tamil Nadu): Relief to Mother and Son | AnnaPurna Muhim',
    location: 'पेरूमबक्कम, कल्लाकुरिची (तमिलनाडु)',
    locationEn: 'Perumbakkam, Kallakurichi (Tamil Nadu)',
    thumbnail: 'https://i.ytimg.com/vi/YceMS7yuG6k/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/YceMS7yuG6k',
    channel: 'AnnaPurna Muhim',
    date: '18 सितम्बर 2026',
    dateEn: 'September 18, 2026',
    description: 'अन्नपूर्णा मुहिम के सेवादारों ने तमिलनाडु के कल्लाकुरिची जिले के पेरूमबक्कम गांव में बेसहारा मां-बेटे तक पहुंचकर राशन एवं बुनियादी जीवनोपयोगी सामग्री की तत्काल सहायता प्रदान की।',
    descriptionEn: 'Annapurna Muhim volunteers reached Perumbakkam village in Kallakurichi, Tamil Nadu, providing immediate ration and essential livelihood support.',
  },
  {
    id: 'annapurna-vid-2',
    videoId: 'jgzDsiHt2PY',
    episode: 'EP-3242',
    title: 'EP-3242 | केशिलम्मा तांडा, विकाराबाद (तेलंगाना): तीसरी बार मिली राहत, बच्चों के चेहरे खिले | AnnaPurna Muhim',
    titleEn: 'EP-3242 | Keshilamma Thanda, Vikarabad (Telangana): 3rd Time Relief Brought Smiles | AnnaPurna Muhim',
    location: 'केशिलम्मा तांडा, विकाराबाद (तेलंगाना)',
    locationEn: 'Keshilamma Thanda, Vikarabad (Telangana)',
    thumbnail: 'https://i.ytimg.com/vi/jgzDsiHt2PY/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/jgzDsiHt2PY',
    channel: 'AnnaPurna Muhim',
    date: '16 सितम्बर 2026',
    dateEn: 'September 16, 2026',
    description: 'विकाराबाद के केशिलम्मा तांडा में लगातार तीसरी बार जरूरतमंद परिवारों तक अन्नपूर्णा राशन किट और पोषण सहायता पहुंचाई गई, जिससे बच्चों के चेहरों पर मुस्कान लौटी।',
    descriptionEn: 'For the third consecutive time, Annapurna ration kits and nutritional support were delivered to underprivileged families in Vikarabad, Telangana.',
  },
  {
    id: 'annapurna-vid-3',
    videoId: 'ZVuZ0i6Oa3c',
    episode: 'EP-3241',
    title: 'EP-3241 | अलिका, सिरसा (हरियाणा): तीन बच्चों संग बेसहारा मां की मदद को पहुंची अन्नपूर्णा मुहिम | AnnaPurna Muhim',
    titleEn: 'EP-3241 | Alika, Sirsa (Haryana): Annapurna Muhim Supported Helpless Mother & 3 Children | AnnaPurna Muhim',
    location: 'अलिका, सिरसा (हरियाणा)',
    locationEn: 'Alika, Sirsa (Haryana)',
    thumbnail: 'https://i.ytimg.com/vi/ZVuZ0i6Oa3c/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/ZVuZ0i6Oa3c',
    channel: 'AnnaPurna Muhim',
    date: '14 सितम्बर 2026',
    dateEn: 'September 14, 2026',
    description: 'सिरसा जिले के अलिका गांव में 3 मासूम बच्चों के साथ जीवन यापन कर रही बेसहारा मां के परिवार को अन्नपूर्णा मुहिम द्वारा दीर्घकालिक राशन व वस्त्र सेवा दी गई।',
    descriptionEn: 'Annapurna Muhim provided sustained ration and clothing support to a helpless mother raising 3 young children in Alika village, Sirsa.',
  },
  {
    id: 'annapurna-vid-4',
    videoId: '4pJ1zezBTqA',
    episode: 'EP-3240',
    title: 'EP-3240 | डांगी, रुद्रप्रयाग(उत्तराखंड): एक पैर गंवाने के बाद पत्नी की किडनी फेल, फिर पहुंची मदद | AnnaPurna Muhim',
    titleEn: 'EP-3240 | Dangi, Rudraprayag (Uttarakhand): Lifeline Reached Afflicted Family | AnnaPurna Muhim',
    location: 'डांगी, रुद्रप्रयाग (उत्तराखंड)',
    locationEn: 'Dangi, Rudraprayag (Uttarakhand)',
    thumbnail: 'https://i.ytimg.com/vi/4pJ1zezBTqA/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/4pJ1zezBTqA',
    channel: 'AnnaPurna Muhim',
    date: '12 सितम्बर 2026',
    dateEn: 'September 12, 2026',
    description: 'पहाड़ी दुर्गम क्षेत्र डांगी (रुद्रप्रयाग) में गंभीर बीमारियों व लाचारी से जूझ रहे परिवार तक अन्नपूर्णा दल ने पहुंचकर खाद्य सामग्री और आवश्यक सहायता सुनिश्चित की।',
    descriptionEn: 'Annapurna team reached the remote hilly hamlet of Dangi in Rudraprayag, ensuring ration and vital medical support to a severely afflicted family.',
  },
  {
    id: 'annapurna-vid-5',
    videoId: 'qm-b8ot8CE4',
    episode: 'EP-3236',
    title: 'EP-3236 | नडियाली,अंबाला (हरियाणा): बेसहारा दादी और 2 बच्चों को मिला अन्नपूर्णा मुहिम का सहारा | AnnaPurna Muhim',
    titleEn: 'EP-3236 | Nadiyali, Ambala (Haryana): Support to Helpless Grandmother & 2 Children | AnnaPurna Muhim',
    location: 'नडियाली, अंबाला (हरियाणा)',
    locationEn: 'Nadiyali, Ambala (Haryana)',
    thumbnail: 'https://i.ytimg.com/vi/qm-b8ot8CE4/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/qm-b8ot8CE4',
    channel: 'AnnaPurna Muhim',
    date: '10 सितम्बर 2026',
    dateEn: 'September 10, 2026',
    description: 'अंबाला के नडियाली गांव में वृद्ध दादी द्वारा पाले जा रहे दो अनाथ बच्चों को अन्नपूर्णा मुहिम ने अपनाया और उनके भरण-पोषण की पूरी जिम्मेदारी उठाई।',
    descriptionEn: 'In Nadiyali village, Ambala, an elderly grandmother caring for two children received comprehensive nutritional and educational support from Annapurna Muhim.',
  },
  {
    id: 'annapurna-vid-6',
    videoId: 'XJ-PcmJEAkQ',
    episode: 'EP-3233',
    title: 'EP-3233 | उपरली वभान, पाली (राजस्थान): 5 बच्चों संग संघर्ष कर रही सुमित्रा को मिला सहारा | AnnaPurna Muhim',
    titleEn: 'EP-3233 | Uparli Vabhan, Pali (Rajasthan): Support to Sumitra Struggling with 5 Children | AnnaPurna Muhim',
    location: 'उपरली वभान, पाली (राजस्थान)',
    locationEn: 'Uparli Vabhan, Pali (Rajasthan)',
    thumbnail: 'https://i.ytimg.com/vi/XJ-PcmJEAkQ/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/XJ-PcmJEAkQ',
    channel: 'AnnaPurna Muhim',
    date: '08 सितम्बर 2026',
    dateEn: 'September 08, 2026',
    description: 'पाली (राजस्थान) के उपरली वभान में पांच छोटे बच्चों के साथ अत्यधिक निर्धनता में संघर्ष कर रही सुमित्रा देवी के घर अन्नपूर्णा सेवादारों ने राशन व घरेलू सामान पहुंचाया।',
    descriptionEn: 'In Uparli Vabhan, Pali, Rajasthan, Sumitra Devi, struggling with 5 children in extreme poverty, received ration kits and household essentials.',
  },
  {
    id: 'annapurna-vid-7',
    videoId: 'hJhB7Fpn2os',
    episode: 'EP-3231',
    title: 'EP-3231  | चित्तौड़ा, इंदौर: बिना बिजली और बाथरूम के रहती थीं गीताबाई, अब मिली पूरी सुविधा | AnnaPurna Muhim',
    titleEn: 'EP-3231 | Chittoda, Indore: Full Facilities Provided to Gitabai Living Without Amenities | AnnaPurna Muhim',
    location: 'चित्तौड़ा, इंदौर (मध्य प्रदेश)',
    locationEn: 'Chittoda, Indore (Madhya Pradesh)',
    thumbnail: 'https://i.ytimg.com/vi/hJhB7Fpn2os/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/hJhB7Fpn2os',
    channel: 'AnnaPurna Muhim',
    date: '06 सितम्बर 2026',
    dateEn: 'September 06, 2026',
    description: 'इंदौर के चित्तौड़ा में बिना बिजली व मूलभूत सुविधाओं के टूटे मकान में रहने वाली बुजुर्ग गीताबाई को अन्नपूर्णा मुहिम ने छत की मरम्मत, बिजली और राशन की पूरी सुविधा दी।',
    descriptionEn: 'In Chittoda, Indore, elderly Gitabai living without electricity or basic amenities was provided full shelter rehabilitation, electricity, and ration.',
  },
  {
    id: 'annapurna-vid-8',
    videoId: 'k_t4rAc9xl4',
    episode: 'EP-3230',
    title: 'EP-3230 | नरखेड़, बैतूल (मध्य प्रदेश): बच्चों की पढ़ाई रुकी नहीं, जरूरतमंद परिवार को मिली पूरी मदद | AnnaPurna Muhim',
    titleEn: 'EP-3230 | Narkhed, Betul (MP): Education Continued & Full Aid Provided to Needy Family | AnnaPurna Muhim',
    location: 'नरखेड़, बैतूल (मध्य प्रदेश)',
    locationEn: 'Narkhed, Betul (Madhya Pradesh)',
    thumbnail: 'https://i.ytimg.com/vi/k_t4rAc9xl4/hqdefault.jpg',
    youtubeUrl: 'https://youtu.be/k_t4rAc9xl4',
    channel: 'AnnaPurna Muhim',
    date: '04 सितम्बर 2026',
    dateEn: 'September 04, 2026',
    description: 'बैतूल (मध्य प्रदेश) के नरखेड़ में आर्थिक तंगी के कारण बच्चों की पढ़ाई छूटने की कगार पर थी; अन्नपूर्णा मुहिम ने किताबें, स्कूल फीस और राशन देकर शिक्षा जारी रखवाई।',
    descriptionEn: 'In Narkhed, Betul (MP), where children faced dropping out of school due to acute hardship, Annapurna Muhim provided study kits and complete family relief.',
  },
];

// Latest verified updates (strictly from official Annapurna Muhim Ground Seva YouTube Episodes)
export const UPDATES_DATA: UpdateItem[] = ANNAPURNA_VIDEOS.map((v) => ({
  id: `up-${v.videoId}`,
  title: v.title,
  titleEn: v.titleEn,
  date: v.date,
  dateEn: v.dateEn,
  image: v.thumbnail,
  description: v.description,
  descriptionEn: v.descriptionEn,
  category: 'अन्नपूर्णा सेवा अपडेट',
  categoryEn: 'Annapurna Seva Update',
  youtubeUrl: v.youtubeUrl,
  channel: 'AnnaPurna Muhim',
  videoId: v.videoId,
}));

// FAQ items
export const FAQ_DATA: FAQItem[] = [
  {
    id: 'f1',
    question: 'जगत उद्धारक मंच का मुख्य उद्देश्य क्या है?',
    questionEn: 'What is the primary objective of the Jagat Uddharak platform?',
    answer: 'जगत उद्धारक मंच का मुख्य उद्देश्य सम्पूर्ण मानव समाज को पवित्र सद्ग्रंथों (वेद, गीता, कुरान, बाइबल, गुरु ग्रंथ साहिब) पर आधारित सच्चा तत्वज्ञान प्रदान करना, समाज से नशा, दहेज व कुरीतियों को समाप्त करना तथा अन्नपूर्णा मुहिम के माध्यम से जरूरतमंदों की निस्वार्थ सेवा करना है।',
    answerEn: 'The primary mission of Jagat Uddharak is to bestow authentic scripture-proven spiritual truth, eliminate social vices such as dowry and addiction, and serve needy individuals unconditionally through the Annapurna Mission.',
    category: 'सामान्य',
    categoryEn: 'General',
  },
  {
    id: 'f2',
    question: 'प्रतिदिन शाम 7:30 बजे का लाइव कार्यक्रम कहाँ और कैसे देखें?',
    questionEn: 'Where and how can we watch the Daily Live Satsang at 7:30 PM IST?',
    answer: 'प्रतिदिन शाम 7:30 बजे से 8:30 बजे (IST) तक जगत उद्धारक के आधिकारिक YouTube चैनल (@JagatUddharak) पर लाइव कार्यक्रम प्रसारित होता है। आप वेबसाइट के DAILY LIVE सेक्शन में "LIVE देखें →" बटन पर क्लिक करके सीधे जुड़ सकते हैं।',
    answerEn: 'The live discourse is broadcast every evening from 7:30 PM to 8:30 PM IST exclusively on the official Jagat Uddharak YouTube channel (@JagatUddharak). You can click the "Watch LIVE" button in the Daily Live section to tune in.',
    category: 'लाइव कार्यक्रम',
    categoryEn: 'Daily Live',
  },
  {
    id: 'f3',
    question: 'अन्नपूर्णा मुहिम क्या है और इसमें किन्हें सहायता दी जाती है?',
    questionEn: 'What is the Annapurna Mission and who receives support under it?',
    answer: 'अन्नपूर्णा मुहिम (annapurnamuhim.com) एक मानवीय सेवा अभियान है जिसके अंतर्गत ऐसे बेसहारा, दिव्यांग, अनाथ बच्चे या बुजुर्ग परिवार जिनके पास भोजन या आवास का कोई साधन नहीं है, उनके घर-घर तक सेवादार पहुंचकर निःशुल्क शुद्ध राशन, कपड़े, चिकित्सा व आवास सहायता उपलब्ध कराते हैं। इसमें कोई दान स्वीकार नहीं किया जाता।',
    answerEn: 'Annapurna Muhim (annapurnamuhim.com) is an unconditional humanitarian initiative delivering free monthly rations, clothing, medical aid, and shelter to disabled, elderly, and orphaned families. It strictly refuses any donations or public funds.',
    category: 'मानव सेवा',
    categoryEn: 'Humanitarian Service',
  },
  {
    id: 'f4',
    question: 'क्या आध्यात्मिक पुस्तकें जैसे "ज्ञान गंगा" व "जीने की राह" निःशुल्क हैं?',
    questionEn: 'Are sacred spiritual books like "Gyan Ganga" and "Way of Living" completely free?',
    answer: 'हाँ! जगतगुरु संत रामपाल जी महाराज द्वारा रचित "ज्ञान गंगा", "जीने की राह", "अंध श्रद्धा भक्ति" आदि सभी प्रमुख पुस्तकें वेबसाइट के पुस्तकें सेक्शन में ऑनलाइन निःशुल्क पढ़ने तथा आधिकारिक PDF डाउनलोड करने के लिए उपलब्ध हैं।',
    answerEn: 'Yes! All major books authored by Jagatguru Sant Rampal Ji Maharaj, including "Gyan Ganga" and "Way of Living", are available for free online reading and official PDF download in the Books section.',
    category: 'साहित्य',
    categoryEn: 'Sacred Literature',
  },
  {
    id: 'f5',
    question: 'संत रामपाल जी महाराज किस परमात्मा की भक्ति बताते हैं?',
    questionEn: 'Which Supreme God does Sant Rampal Ji Maharaj guide to worship?',
    answer: 'संत रामपाल जी महाराज चारों वेदों, श्रीमद्भगवद्गीता, पवित्र कुरान, पवित्र बाइबल और श्री गुरु ग्रंथ साहिब के प्रमाणों सहित बताते हैं कि सर्वशक्तिमान, अमर और कुल के मालिक पूर्ण परमेश्वर कबीर साहेब (कविर्देव) हैं, जो सतलोक (अमरलोक) के अधिपति हैं।',
    answerEn: 'Sant Rampal Ji Maharaj demonstrates with documentary scripture evidence from the Vedas, Gita, Quran, Bible, and Guru Granth Sahib that the supreme immortal creator is Supreme God Kabir (KavirDev), master of Satlok.',
    category: 'तत्वज्ञान',
    categoryEn: 'Spiritual Truth',
  },
  {
    id: 'f6',
    question: 'नामदान (दीक्षा) प्राप्त करने के क्या नियम हैं?',
    questionEn: 'What are the core prerequisites for receiving spiritual initiation (Naamdaan)?',
    answer: 'नामदान प्राप्त करने के लिए भक्त को सभी प्रकार के नशे (शराब, तंबाकू, बीड़ी आदि) तथा मांसाहार का पूर्ण त्याग करना होता है। किसी अन्य देवी-देवता की शास्त्रविरुद्ध पूजा नहीं करनी होती और मर्यादा में रहकर सुमिरन करना होता है। नामदान पूर्णतः निःशुल्क प्रदान किया जाता है।',
    answerEn: 'Initiation requires complete lifelong abstinence from all intoxicants, gambling, and meat consumption, adhering to scriptural guidelines, and practicing sincere meditation. Initiation is always 100% free.',
    category: 'दीक्षा',
    categoryEn: 'Initiation',
  },
];

// Official Ashram contacts - STRICTLY EXCLUDES ANY BARWALA / HISAR INFORMATION
export const ASHRAM_CONTACTS: AshramContact[] = [
  {
    id: 'dhanana',
    name: 'सतलोक आश्रम धनाना धाम',
    nameEn: 'Satlok Ashram Dhanana Dham',
    location: 'सोनीपत, हरियाणा',
    locationEn: 'Sonipat, Haryana',
    address: 'गोहाना-जींद रोड, धनाना, जिला सोनीपत (हरियाणा)',
    addressEn: 'Gohana-Jind Road, Dhanana, District Sonipat, Haryana',
    phoneNumbers: ['+91 8222880543', '+91 8222880544'],
  },
  {
    id: 'kurukshetra',
    name: 'सतलोक आश्रम कुरुक्षेत्र',
    nameEn: 'Satlok Ashram Kurukshetra',
    location: 'कुरुक्षेत्र, हरियाणा',
    locationEn: 'Kurukshetra, Haryana',
    address: 'पिपली रोड, कुरुक्षेत्र (हरियाणा)',
    addressEn: 'Pipli Road, Kurukshetra, Haryana',
    phoneNumbers: ['+91 8222880545'],
  },
  {
    id: 'bhiwani',
    name: 'सतलोक आश्रम भिवानी',
    nameEn: 'Satlok Ashram Bhiwani',
    location: 'भिवानी, हरियाणा',
    locationEn: 'Bhiwani, Haryana',
    address: 'रोहतक-भिवानी मार्ग, भिवानी (हरियाणा)',
    addressEn: 'Rohtak-Bhiwani Highway, Bhiwani, Haryana',
    phoneNumbers: ['+91 8222880541'],
  },
  {
    id: 'shamli',
    name: 'सतलोक आश्रम शामली',
    nameEn: 'Satlok Ashram Shamli',
    location: 'शामली, उत्तर प्रदेश',
    locationEn: 'Shamli, Uttar Pradesh',
    address: 'करनाल-मेरठ हाईवे, शामली (उत्तर प्रदेश)',
    addressEn: 'Karnal-Meerut Highway, Shamli, Uttar Pradesh',
    phoneNumbers: ['+91 8222880542'],
  },
];
